### ISSUE TITLE
Fatal: Uncaught exception Error: spawn pdftk ENOENT

### ISSUE THREAD

**Issue by JohnnySpomer** [thr-consulting/thr-addons#189]
Get this error when trying to use the pdfform library.
```
Fatal: Uncaught exception Error: spawn pdftk ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn pdftk',
  path: 'pdftk',
  spawnargs: [
    '/home/jonathan/documents/thr4/packages/server/assetsServer/binder/accountingfeesform.pdf',
    'fill_form',
    '-',
    'output',
    '-',
    'flatten'
  ]
}
```

**Comment by darkadept** [comment]
need to install pdftk
